INSERT INTO USER (USERNAME, PASSWORD) VALUES ('sam', '$2a$11$c9HEOZYL7r08xfLNHDM5Bufcp5y5mitB9hOm3wg8Gsn.ochs1GRq6');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('tom', '$2a$11$c9HEOZYL7r08xfLNHDM5Bufcp5y5mitB9hOm3wg8Gsn.ochs1GRq6');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('sam', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('sam', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('tom', 'USER');